### PR TITLE
Cleanup to make for easier triage

### PR DESCRIPTION
**Pull request by faddat**
- add code quality tooling that was removed by l1 team
- tidy and go 1.20
- begin cleanup (again).  Linting makes issues more obvious, gives them fewer places to hide
- Literally takes the cleanliness of the repository back to the way it was over four months ago.  Standards matter.

## Summary of changes

This PR reintroduces various pieces of automated code quality tooling, and bumps go in all places to v1.20.1

**this should be released as v1.1.1 and ALL VALIDATORS should attempt to use this build.  If this resolves the issue, then the problem was the go version.**

This PR begins from #159 and will soon have restored rigor to the repository.

Pursuant to #158 

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by ZaradarBH** [comment]
Dear Jacob,

We have been busy with the upgrade, as well as other distractions, hence the late reply.

The PR is indeed the same one I approved on the TR repo back in October 2022, which also included other goodies like the IBC 3.4 update. However in the course of testing the client @inon-man found that upgrading to Go 1.20 causes the compiled terrad binary to produce an AppHash error when synchronizing from genesis due to some undetermined source of non-determinism in Go 1.20. This means that for the time being we havee agreed to stick with Go 1.18 until we have had a chance to complete the existing upgrade work and assert if the bump to Cosmos SDK v0.45.13 will fix the root cause of the non-deterministic behavior and allow us to bump Go to 1.20. So in short, stick with Go 1.18.

In addition seeing how we are in the process of upgrading to Cosmos SDK v0.45.13, it might make more sense for you to clean up that code once the PR has been completed, using the "go fumpt" or any other "code formatter" you prefer. Just make sure you test it extensively as this type of "auto refactoring" can lead to unintended consequences which can potential break our state machine. To put it in perspective, the "auto refactoring" of Go from v1.18 to v1.20 ended up costing us 2 days of debugging and another 7 days of testing waiting for  the client to sync from the Columbus-5 genesis. 

To conclude I would suggest that you close this PR and open up a new one after we are done with the terrad 2.0 milestone, if you feel a need to clean up the code further 🙏

**Comment by faddat** [comment]
Well I mean I suppose that he did not try a network that was entirely 1.20 which is why you should be upgrading to the latest version of go at every single state breaking change, that is to say every coordinated release.

**Comment by ZaradarBH** [comment]
> Well I mean I suppose that he did not try a network that was entirely 1.20 which is why you should be upgrading to the latest version of go at every single state breaking change, that is to say every coordinated release.
> 
> The danger my friends, you see, comes from very specifically having mixed go run times, same as the danger that comes from releasing the same tag twice, you see, every single block must arrive at precisely the same hash or you get the app hashes of doom.
> 
> Thus it seems to me that you have missed yet another opportunity to make the network more reliable and robust by fixing on the latest version of go to ensure that app hashes are impossible

Have you actually tested this assumption of syncing the columbus-5 genesis in a testnet with a group of validators to see if everyone running Go 1.20 fixes the problem? My point being that we have other things we need to prioritize and we would rather focus on setting up the kind of test automation that can make these tests for us and given that we know v1.18 does the trick there is no reason to add more to our current focus. Once we have completed the cosmwasm 1.2.0+ upgrade we can look into this if there are not more pressing concerns and it is as you say indeed "just" a matter of getting all the valiators to upgrade to Go 1.20.

**Comment by faddat** [comment]
@ZaradarBH -- I've merged main.  Please note that among other things that this PR does, it adds a lot of error checks.  This is useful, for catching issues before they happen.

**Comment by ZaradarBH** [comment]
> @ZaradarBH -- I've merged main. Please note that among other things that this PR does, it adds a lot of error checks. This is useful, for catching issues before they happen.
> 
> It just doesn't seem unreasonable to throw as many tools as possible at the task, so that the humans can focus on more serious items than what a linter or static analysis tool might discover on its own.

I have no problem with "auto refactoring" and in that context I can highly suggest that you try out GitHub Co-pilot, for a lack of a better words its simply amazing. It cant really produce functional code due to the "dependency inconsistency" between minor version in Cosmos SDK, which I believe we have discussed in the past and is an area where we seem to agree. The point I am trying to get to here is that while the process of "auto refactoring" is as you say a "force multiplier" due to the state of Cosmos SDK it unfortunately seems to lead to breaking changes from time to time. I have noticed this happen over the last 8 months with dependabot, snyk-bot. go fumpt and manual changes to go.mod. So we just need to remember to test things extensively which is why @nghuyenthevinh2000 and I are working on a E2E testing framework that can spin up two new networks in k8s and do full regression testing including IBC, UI, etc. As the process of testing these "state machine alterations", no matter how small the change, is insanely time consuming if we want to ensure the integrity of our blockchain and that overall makes us less productive as devs, hence my focus on the terra operator concept and k8s in general.

We are about to merge 0.45.13 into main later today, we just need a 2nd reviewer, your more then welcome to pitch in in that PR. Once that is done we should re-merge main and bring in your PR to clean-up the remaining broken windows, I would however ask that you downgrade go to 1.18 so we do not have to deal with that particular test burden until we are past the 2.0 release. At which point we should also have the E2E test stuff in a beta state so we can leverage that to test the assumption that in a network of validators who all run 1.20 we will not experience an AppHash error when syncing from the Columbus-5 genesis

**Comment by faddat** [comment]
You should not use go 1.18, it has reached end of life, see the SDK 46 release notes:

https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.11

You should not use go 1.18

**Pull request closed without merging**
