### PR TITLE
feat: FeeDecorator

### PR DESCRIPTION
**Pull request by inon-man**
## Description
This PR adds a new Ante handler `FeeDecorator` that merges TaxFeeDecorator, BurnTaxFeeDecorator, and DeductFeeDecorator of CosmosSDK. This is required for allowing validators to submit oracle vote transactions without fee.

Closes: #330

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
@inon-man I think it needs one more oracle submit tx test to make sure. Let's me add that one in

**Comment by fragwuerdig** [comment]
One question. Does this `FeeDecorator` deduct the taxes from the account balance rather than deducting it from the fee field of the tx. Did I read that correctly?

**Comment by nghuyenthevinh2000** [comment]
> One question. Does this `FeeDecorator` deduct the taxes from the account balance rather than deducting it from the fee field of the tx. Did I read that correctly?

fee is collected first to FeeCollector, then tax is get from FeeCollector

**Review by nghuyenthevinh2000 — APPROVED** [review]

**Comment by nghuyenthevinh2000** [comment]
@inon-man please check again before merge. I am all good.

**Pull request merged**
