### PR TITLE
Revert "Constrained pool to ensure LUNC can never have more then 2T supply"

### PR DESCRIPTION
**Pull request by inon-man**
Reverts classic-terra/core#51

### CODE REVIEW

**Comment by inon-man** [comment]
This wasn't reviewed enough

**Comment by lehajam** [comment]
Thank you ! In fact the PR was utterly wrong and I was about to push a PR to revert it myself. 

```askPool = ConstrainedPool{Pool: lunaPool, MaxSize: sdk.NewDec(2000000000000)}```

The unit is in micro SDR !! So in this case @ZaradarBH put a constraint of 2M SDR on the pool size, **NOT** 2T. That's why it did not work when he tried 10B since it really was a limit of 10K SDR and it broke some tests. 

Besides, **the size of the pool has nothing to do with the total supply !!!** This is simply a limit on the size of the liquidity pool and in a way on the amount of tokens which can be minted **per swap**. You could still swap multiple times, and with the swap enabled, mint close to 2T LUNC per swap !!

Well done on that one @inon-man

**Comment by ZaradarBH** [comment]
I asked for this to be reviewed for days with no feedback from anyone so I decided to merge it so we could focus on new stuff. As such it is not meant to limit the size of the pool. Its meant to avoid the pool going above a certain size. 

Furthermore I have already stated a number of times that the number imposed was the minimum amount you can supply without changing a ton of tests and seeing how this is not scheduled for release for a month there is no reason to revert it. Simply change the logic to the value you think is adequate and make a new PR :)

**Comment by inon-man** [comment]
It is just your test and it does not mean it has been proved. No blockchain works like that and no one will trust the software managed like a personal toy.

**Comment by inon-man** [comment]
I raised multiple woes about this and you just did not listen to what I said Tobias. If you are not trying to be another villion, stop doing it.

**Pull request merged**
