### PR TITLE
feat(treasury): split the burn tax to the distribution module

### PR DESCRIPTION
**Pull request by alchemist-ti**
## Summary of changes

Proposal link: https://station.terrarebels.net/proposal/11513
Closes: #232 

## Report of required housekeeping

- [x] Github issue OR spec proposal link
- [x] Wrote tests
- [x] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [x] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [x] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by alchemist-ti** [comment]
Cosmos AllocateTokens from FeeCollector: https://github.com/cosmos/cosmos-sdk/blob/v0.45.13/x/distribution/keeper/allocation.go#L16.

Seems should split the Burn tax to the FeeCollector? @fragwuerdig @nghuyenthevinh2000 @inon-man

**Comment by alchemist-ti** [comment]
After a token transfer transaction of `usdr`, the burn tax is distributed to validators and community pools.
test

**Comment by alchemist-ti** [comment]
> Isn't it intended? Any issue?

@inon-man No, it's my test result, and it is the expected result.

**Comment by LuncBurner** [comment]
@nghuyenthevinh2000 @fragwuerdig Can you guys review?

**Review by nghuyenthevinh2000 — APPROVED** [review]
I have checked over, LGTM!

**Pull request merged**
