### PR TITLE
ci: add codeql ci

### PR DESCRIPTION
**Pull request by nghuyenthevinh2000**
## Summary of changes

Add codeql ci from crypto-com

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
@inon-man @ZaradarBH @fragwuerdig 

This might interest you. This is codeql ci standard that most cosmos chains use. It will scan the codebase to check for problems.

Like this one

Screenshot 2023-02-17 at 19 00 37

**Comment by ZaradarBH** [comment]
Can you look at adding in the SNYK actions as well? :) We have an org you can join here @ https://app.snyk.io/org/l1-task-force/ and here is the location of the SNYK actions @ https://github.com/snyk/actions

**Review by ZaradarBH — APPROVED** [review]
LGTM :)

**Comment by inon-man** [comment]
Interesting but all of them are informative. We need to check that snoozed issue doesn't pops up again.

**Review by edk208 — APPROVED** [review]

**Comment by nghuyenthevinh2000** [comment]
:)) oh wait, I have not deleted the invoking print line

**Pull request merged**
