### PR TITLE
enable swap

### PR DESCRIPTION
**Pull request by faddat**
## Summary of changes

This PR enables the swap mechanism for Luna classic.  It is untested and comes with no warranty whatsoever. 

I just thought that it would be fun to write. 

Those interested in bringing it back should make a governance proposal specifying a commit that reflects the merge of this PR. 

LUNC has no canonical repository.  The repository does not need to be this one. 

This **is** a political statement.  Good day.

## Notes

* it is set to upgrade at the JusticeAndTruthHeight: 13369420
* iirc somewhere the price of ust is fixed to a dollar, consider changing it to some value below its current market value, but not more than 1/3rd less
* it is probably tempting to make the swap/ust setup more complicated, but I don't recommend that.  
* If validators are feeling rebellious, this doesn't actually need to pass governance.  Just set a height to activate and swap out the binary.  Please note that there was never a gov prop to disable swap.  So it should be enabled no matter what gov says. 
* If validators are not feeling rebellious, then a gov prop could be needed

## Disclaimer

This code could literally kill LUNC the zombie chain or shoot your dog like an american cop.  Notional is leaving the validator set with no intention of ever coming back.  Nonetheless, we truly wish the community well and upon consideration, reenabling the swap mechanism seemed to me to be the most sensible path forward for this chain/community.

## Report of required housekeeping

- [x] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by faddat** [comment]
I will not be squashing my commits but you may squash them when merging.

**Comment by nghuyenthevinh2000** [comment]
I found no change in market module or wasm bindings except for linting. Gonna mark this as draft.

Screenshot 2023-06-19 at 10 29 29

**Comment by faddat** [comment]
Either, you may wish to consider that there are exercises for the reader in here. I am not claiming that all the things in the list are done.

This is my last contribution to LUNC, I fully expected it to sit here unused like the others.

I believe that the notes to the pull request very clearly state that the validators can run this without any approval from anybody because it was never approved to turn this module off. I believe that the notes also very very clearly state that it is left is an exercise for the reader.

❣️

**Comment by fragwuerdig** [comment]
The swap can be re-enabled using parameter change proposal and setting `MinSpread` < 1 using governance. Thank you anyway, Jacob.

**Pull request closed without merging**
