### PR TITLE
cleanup go.mod

### PR DESCRIPTION
**Pull request by faddat**
## Summary of changes

Cleans up go.mod in v0.45.13-proposal

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by ZaradarBH** [comment]
This PR bumps to Go 1.20 which you have been told repeatedly not to do. It removes security replacements simply because you for refuse to listen and it seems to do stuff that is already being done in another PR. So overall this PR really makes no sense. 

We can discuss your auto refactoring suggestions on the other PR and do whatever go.mod changes you feel is needed after we are done merging the 45.13 PR and done discussing your change requests.

**Comment by faddat** [comment]
Sir it did a hell of a lot more than that.  

Now, you're still against either 1.19 and 1.20?

**Comment by ZaradarBH** [comment]
You are not listening to what I am telling you and I do not have time to entertaining your adolescence Jacob. If you want to provide constructive feedback listen to what your being told, dont put words in peoples mouth. What your being told is that we will not be bumping to Go 1.19+ in 2.0 or 2.1. Accept it or not. That is largely irrelevant to us 🙏

**Comment by faddat** [comment]
that is correct Tobias, I am not listening to you when you say things that aren't valid.

**Pull request closed without merging**
