### PR TITLE
Add remaining old Astroport Classic contracts

### PR DESCRIPTION
**Pull request by Mycetism**
## Summary of changes

Added remaining old [Astroport Classic contracts](https://web.archive.org/web/20230327174244/https://docs.astroport.fi/docs/develop/smart-contracts/contract-addresses#terra-classic) according to https://github.com/classic-terra/core/issues/362.

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
can you post contract hash so that I knew that these contracts are from current mainnet?

**Comment by fragwuerdig** [comment]
Thank you. What is this supposed to solve @Mycetism? Can you reference the issue, please?

**Comment by Mycetism** [comment]
> can you post contract hash so that I knew that these contracts are from current mainnet?

| File              | Code ID | Contract Address                             | Computed Checksum                                                |
| :---------------- | ------: | :------------------------------------------- | :--------------------------------------------------------------- |
| assembly.wasm     |    4169 | terra1sq9ppsvt4k378wwhvm2vyfg7kqrhtve8p0n3a6 | DF66B4E622420F5A97AA8AA5E944DA6286425BB75B054CBEFAE422849B52BEB4 |
| cw20_token.wasm   |    1796 |                                              | 427BDC4D07DD7AB31AFFBF19BE540135AAA6CB4EDBC372759AB2034960D1386E |
| factory.wasm      |    4006 | terra1fnywlw4edny3vw44x04xd67uzkdqluymgreu7g | D87EB0DF4CA07562D78C297FA62B9D426E53CE05823CA63B0712E074C49683E4 |
| generator.wasm    |    2671 | terra1zgrx9jjqrfye8swykfgmd6hpde60j0nszzupp9 | 6BA9954319CB2CE9C4F4F76B6481163C22053191FD8D44FC4EA0F9758FC7BB81 |
| maker.wasm        |    4012 | terra12u7hcmpltazmmnq0fvyl225usn3fy6qqlp05w0 | 4D2EA68434681D578A5FF7288E619B78B9E6836857E9FA1E964D69C29939A2AD |
| pair.wasm         |    1793 |                                              | C8BE6039AC70DD5D71B9C5D1A70BBBFD8FEDA71AD8C6573DFDE0FCE32DA4C6C5 |
| pair_stable.wasm  |    4007 |                                              | 4B8D603F4EB517B53577D37425B5CBC1059056121BC71A05CA03A5987EA7234D |
| router.wasm       |    2818 | terra16t7dpwwgx9n3lq6l6te3753lsjqwhxwpday9zx | 8A45B4D663D8FE2600EE700B4EEF70062467CD10801AFC4EADA1C74FC01BB5E9 |
| staking.wasm      |    4010 | terra1f68wt2ch3cx2g62dxtc8v68mkdh5wchdgdjwz7 | 628055D06158795F68C832ABC9F060E4245B674B6B0975B143B7183AF8A4F80B |
| vesting.wasm      |    2079 | terra1hncazf652xa0gpcwupxfj6k4kl4k4qg64yzjyf | 85CB4986A283FCFF31FF5468227E2D7AA951764D9CB66A53BE56E0FF761E3FE9 |
| xastro_token.wasm |    4009 | terra14lpnyzc9z4g3ugr4lhm8s4nle0tq8vcltkhzh7 | 26ACBBA9D890E5F607B80004B03C6781E5BBCA4113E55B4C6FCAA722C7EB8275 |

**Review by nghuyenthevinh2000 — APPROVED** [review]
checked, looks good to me. Can you work on the JS script to deploy these contracts to testnet?

https://github.com/classic-terra/astroport-core/blob/terra_classic_invictus_v2/scripts/deploy_core.ts

you will find all JS script that Astroport team uses to deploy their contracts

**Pull request merged**
