### PR TITLE
remove conditionals from ci

### PR DESCRIPTION
**Pull request by faddat**
# Code quality initiative led by Notional Labs

Delegations to Notional Labs on LUNC and other cosmos chains fund this work.

## Summary of changes

Removes conditionals from CI as part of a code 
quality initiative brought to LUNC by Notional Labs.

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by faddat** [comment]
@fragwuerdig sir, when was it that y'all reverted... basically all the work I ever did on lunc?

**Comment by faddat** [comment]
Almost none of the ci jobs were actually running.

@fragwuerdig @nghuyenthevinh2000

**Comment by fragwuerdig** [comment]
@faddat. Thank you. Let's fix this. I will provide some commits later that day. Probably late night. Can you instead of pull requesting into main pull request into #187? Thank you.

**Comment by fragwuerdig** [comment]
> @fragwuerdig sir, when was it that y'all reverted... basically all the work I ever did on lunc?

No one reverted, Jacob. We just took the v1.0.4 release as new mainline as the old main was instable. Period. You are free to suggest modifications as you please.

**Comment by ZaradarBH** [comment]
We are in the process of rebuilding the entire GH workflow to support automated testing, UI testing, etc. I don't really think it makes any type of sense to invest resources in the old workflows as they will largely be deprecated when we are done with the new CI/CD  pipeline

**Review by ZaradarBH — APPROVED** [review]
LGTM. As stated we are working on a new CI/CD pipeline so most likely most of these workflows will be deprecated or recycled based on their compatibility with the new design

**Review by chengwenxi — APPROVED** [review]

**Comment by nghuyenthevinh2000** [comment]
closing in favor of #270

**Pull request closed without merging**
