### PR TITLE
feat: update wasmvm to 0.16.7

### PR DESCRIPTION
**Pull request by inon-man**
## Summary of changes

<Describe summary of major changes here>

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by inon-man** [comment]
Need to review gas

**Comment by nghuyenthevinh2000** [comment]
This one passes all test normally so doesn't have gas problem. If it does, it should break many gas test.

**Comment by nghuyenthevinh2000** [comment]
I want to add in some benchmark test as well for future upgrade of wasmvm

**Review by ZaradarBH — APPROVED** [review]
LGTM :)

**Review by nghuyenthevinh2000 — APPROVED** [review]

**Pull request merged**
