### PR TITLE
v1.x backport: add burn tax split logic

### PR DESCRIPTION
**Pull request by nghuyenthevinh2000**
## Summary of changes

* Backport burn-tax-split logic to v1.x
* Original work thanks to @ZaradarBH @vuong177 

- [x] Need to have an unit test to check burn tax split logic

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Review by ZaradarBH — APPROVED** [review]

**Comment by ZaradarBH** [comment]
LGTM. Great work buddy :)

**Comment by nghuyenthevinh2000** [comment]
> LGTM. Great work buddy :)

Great comment buddy :))

**Comment by nghuyenthevinh2000** [comment]
Added an unit test to check if:
1. before tax split logic upgrade height, all taxes go to burn module
2. after tax split logic upgrade height, 50% goes to burn module, 50% goes to community pool (50% is split percentage)

@inon-man @ZaradarBH @edk208 can you confirm that it is the correct unit test. I am not sure if I understand the split logic correctly and fully.

**Comment by inon-man** [comment]
I can find param query for burn_tax_split in the commits. Is it intended?

**Comment by nghuyenthevinh2000** [comment]
> I can find param query for burn_tax_split in the commits. Is it intended?

I think it is normal to be able to query all params

**Comment by inon-man** [comment]
> > I can find param query for burn_tax_split in the commits. Is it intended?
> 
> I think it is normal to be able to query all params

I meant I could not find cli and rest query for the parameter unlike the all other treasury parameters.

**Comment by nghuyenthevinh2000** [comment]
> > > I can find param query for burn_tax_split in the commits. Is it intended?
> > 
> > 
> > I think it is normal to be able to query all params
> 
> I meant I could not find cli and rest query for the parameter unlike the all other treasury parameters.

you can find it here

Screenshot 2023-02-11 at 15 11 05

**Comment by inon-man** [comment]
> > > > I can find param query for burn_tax_split in the commits. Is it intended?
> > > 
> > > 
> > > I think it is normal to be able to query all params
> > 
> > I meant I could not find cli and rest query for the parameter unlike the all other treasury parameters.
> 
> you can find it here for burn_tax_split. This is after upgrade test.
> 
> Screenshot 2023-02-11 at 15 11 05
> 

I am aware of it but my question was there is no separate query for burn tax split like othe params for keeping the consistency. I I However, I am okay with not having it because there is no such consistent pattern  between modules Cosmos SDK.

**Review by inon-man — APPROVED** [review]

**Pull request merged**
